name: Governance Sync

on:
  schedule:
    - cron: "0 6 * * *"  # Run daily at 06:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install sqlalchemy python-dotenv google-cloud-storage

      - name: Run Governance Sync
        env:
          PYTHONPATH: src
          GCS_BUCKET: agent-factory-audit
        run: python scripts/sync_governance_logs.py

      - name: Generate Governance Report
        env:
          PYTHONPATH: src
        run: python scripts/generate_governance_report.py

      - name: Upload Governance Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: governance-report
          path: |
            artifacts/governance_report_*.md
            artifacts/audit_digest_*.json
            artifacts/kba_validation.log
          if-no-files-found: warn
