name: Phase 5 Governance Console CI

on:
  push:
  pull_request:

jobs:
  governance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest sqlalchemy python-dotenv numpy
          pip install -r requirements.txt || true
      - name: Run tests
        run: pytest -q
      - name: Generate Governance Report
        run: python scripts/generate_phase5_report.py
      - name: Upload Governance Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: phase5-report
          path: docs/phase5_governance_report.md
