name: Phase 6 Continuous Oversight

on:
  schedule:
    - cron: "0 3 * * *"  # Daily at 03:00 UTC
  workflow_dispatch:

jobs:
  oversight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest sqlalchemy python-dotenv numpy
      - name: Run tests
        run: pytest -q || true
      - name: Emit sample HITL action
        env:
          PYTHONPATH: src
          HITL_DEMO_AGENT: "GovernanceConsole"
          HITL_DEMO_ACTION: "approve"
          HITL_DEMO_REASON: "Scheduled CI oversight"
          HITL_DEMO_APPROVER: "ci-bot"
        run: python -m src.agent_factory.console.hitl_logger
      - name: Retrain Ethical Baseline
        run: python scripts/retrain_ethical_baseline.py
      - name: Upload Oversight Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: phase6-oversight
          path: |
            artifacts/hitl_actions.jsonl
            data/ethical_baseline_v2.json
